version: '2'
name: 'site103_wasaynet'
services:
  jekyll:
    container_name: 'site103_wasaynet-app'
    image: jekyll/jekyll:latest
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '4000'
    environment:
      hostname: 'host.docker.internal'
    command: bundle exec jekyll serve --watch --incremental --config _config.yml --baseurl  --host 0.0.0.0 --force_polling --verbose
